site_name: Python Tutorial
site_url: https://helsoc7.github.io/python-tutorial/
nav:
  - Home: index.md
  - Inhalte: 
    - Chapter 1: 
        - Introduction: chapter1/intro1.md
        - Exercise: chapter1/exercise1.md
    - Chapter 2:
        - Introduction: chapter2/intro2.md
        - Exercise: chapter2/exercise2.md
    - Chapter 3:
      - Introduction: chapter3/intro3.md
      - Exercise: chapter3/exercise3.md
    - Chapter 4:
        - Introduction: chapter4/intro4.md
        - Exercise: chapter4/exercise4.md
    - Chapter 5:
        - Introduction: chapter5/intro5.md
        - Exercise: chapter5/exercise5.md
    - Chapter 6:
        - Introduction: chapter6/intro6.md
        - Exercise: chapter6/exercise6.md
    - Chapter 7:
        - Introduction: chapter7/intro7.md
        - Exercise: chapter7/exercise7.md
theme:
  name: mkdocs
  color_mode: auto
  user_color_mode_toggle: true
  locale: en
  analytics: {gtag: 'G-274394082'}
  highlightjs: true
  hljs_languages:
    - yaml
    - django
