site_name: Python Tutorial
site_url: https://helsoc7.github.io/python-tutorial/
nav:
  - Home: index.md
  - Kapitel 1:
    - Theorie: chapter1/intro.md
    - Aufgaben: chapter1/exercise1.md
  - Kapitel 2:
    - Theorie: chapter2/intro.md
    - Aufgaben: chapter2/exercise2.md