site_name: Python Tutorial
site_url: https://helsoc7.github.io/python-tutorial/
nav:
  - Home: index.md
  - Inhalte: 
    - Kapitel 1: 
        - Theorie: chapter1/example1.md
        - Beispiel: chapter1/example1.md
        - Aufgaben: chapter1/exercise1.md
    - Kapitel 2:
        - Theorie: chapter2/intro2.md
        - Aufgaben: chapter2/exercise2.md
    - Kapitel 3:
      - Theorie: chapter3/intro3.md
      - Aufgaben: chapter3/exercise3.md
    - Kapitel 4:
        - Theorie: chapter4/intro4.md
        - Aufgaben: chapter4/exercise4.md
    - Kapitel 5:
        - Theorie: chapter5/intro5.md
        - Aufgaben: chapter5/exercise5.md
    - Kapitel 6:
        - Theorie: chapter6/intro6.md
        - Aufgaben: chapter6/exercise6.md
    - Kapitel 7:
        - Theorie: chapter7/intro7.md
        - Aufgaben: chapter7/exercise7.md
    - Notebooks: _output/lab/index.html
plugins:
  - mkdocs-jupyter
theme:
  name: mkdocs
  color_mode: auto
  user_color_mode_toggle: true
  locale: de
  analytics: {gtag: 'G-274394082'}
  highlightjs: true
  hljs_languages:
    - yaml
    - django
extra_css:
  - extra.css
  

